# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_drink_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='probiotic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='drink',
            name='protein',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='drink',
            name='vitamin',
            field=models.IntegerField(default=0),
        ),
    ]
